In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import warnings
warnings.filterwarnings("ignore")

In [15]:
data = pd.read_csv("bankloan.csv")
data.head()

ID  Age  Experience  Income  ZIP.Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal.Loan  Securities.Account  CD.Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [16]:
data.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP.Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal.Loan         0
Securities.Account    0
CD.Account            0
Online                0
CreditCard            0
dtype: int64

In [17]:
data.value_counts()

ID    Age  Experience  Income  ZIP.Code  Family  CCAvg  Education  Mortgage  Personal.Loan  Securities.Account  CD.Account  Online  CreditCard
1     25   1           49      91107     4       1.6    1          0         0              1                   0           0       0             1
2     45   19          34      90089     3       1.5    1          0         0              1                   0           0       0             1
3     39   15          11      94720     1       1.0    1          0         0              0                   0           0       0             1
4     35   9           100     94112     1       2.7    2          0         0              0                   0           0       0             1
5     35   8           45      91330     4       1.0    2          0         0              0                   0           0       1             1
                                                                                                                     

In [18]:
data["ZIP.Code"].unique()

array([91107, 90089, 94720, 94112, 91330, 92121, 91711, 93943, 93023,
       94710, 90277, 93106, 94920, 91741, 95054, 95010, 94305, 91604,
       94015, 90095, 91320, 95521, 95064, 90064, 94539, 94104, 94117,
       94801, 94035, 92647, 95814, 94114, 94115, 92672, 94122, 90019,
       95616, 94065, 95014, 91380, 95747, 92373, 92093, 94005, 90245,
       95819, 94022, 90404, 93407, 94523, 90024, 91360, 95670, 95123,
       90045, 91335, 93907, 92007, 94606, 94611, 94901, 92220, 93305,
       95134, 94612, 92507, 91730, 94501, 94303, 94105, 94550, 92612,
       95617, 92374, 94080, 94608, 93555, 93311, 94704, 92717, 92037,
       95136, 94542, 94143, 91775, 92703, 92354, 92024, 92831, 92833,
       94304, 90057, 92130, 91301, 92096, 92646, 92182, 92131, 93720,
       90840, 95035, 93010, 94928, 95831, 91770, 90007, 94102, 91423,
       93955, 94107, 92834, 93117, 94551, 94596, 94025, 94545, 95053,
       90036, 91125, 95120, 94706, 95827, 90503, 90250, 95817, 95503,
       93111, 94132,

In [19]:
data = data.drop(["ID", "ZIP.Code"], axis=1)

In [20]:
# data.head()
data["Personal.Loan"].unique()

array([0, 1])

In [21]:
X = data.drop("Personal.Loan",axis=1)
Y = data['Personal.Loan']

In [22]:
X

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
0      25           1      49       4    1.6          1         0   
1      45          19      34       3    1.5          1         0   
2      39          15      11       1    1.0          1         0   
3      35           9     100       1    2.7          2         0   
4      35           8      45       4    1.0          2         0   
...   ...         ...     ...     ...    ...        ...       ...   
4995   29           3      40       1    1.9          3         0   
4996   30           4      15       4    0.4          1        85   
4997   63          39      24       2    0.3          3         0   
4998   65          40      49       3    0.5          2         0   
4999   28           4      83       3    0.8          1         0   

      Securities.Account  CD.Account  Online  CreditCard  
0                      1           0       0           0  
1                      1           0       0           0  
2                      0           0       0           0  
3                      0           0       0           0  
4                      0           0       0           1  
...                  ...         ...     ...         ...  
4995                   0           0       1           0  
4996                   0           0       1           0  
4997                   0           0       0           0  
4998                   0           0       1           0  
4999                   0           0       1           1  

[5000 rows x 11 columns]

In [23]:
Y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal.Loan, Length: 5000, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,Y_train,Y_test =  train_test_split(X,Y,test_size=0.3)

In [26]:
X_train.shape,X_test.shape

((3500, 11), (1500, 11))

In [27]:
Y_train.shape,Y_test.shape

((3500,), (1500,))

#Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion="entropy")
rfc_model = rfc.fit(X_train,Y_train)
rfc_model

RandomForestClassifier(criterion='entropy')

In [29]:
rfc_pred = rfc.predict(X_test)
rfc_pred[:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
accuracy_score(Y_test,rfc_pred)*100

98.66666666666667

#  Normalization of the Data

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [32]:
X_train,X_test,Y_train,Y_test = train_test_split(X_scaled,Y,test_size=0.3)

In [33]:
X_train.shape,X_test.shape

((3500, 11), (1500, 11))

In [34]:
Y_train.shape,Y_test.shape

((3500,), (1500,))

# Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_model = log_reg.fit(X_train,Y_train)
log_model

LogisticRegression()

In [36]:
Log_pred = log_reg.predict(X_test)
Log_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [37]:
accuracy_score(Y_test,Log_pred)*100

94.66666666666667

# Decision tree

In [38]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt_model = dt.fit(X_train,Y_train)
dt_model

DecisionTreeClassifier()

In [39]:
dt_pred = dt.predict(X_test)
dt_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [40]:
accuracy_score(Y_test,dt_pred)*100

98.6

# K-Nearest neighbour

In [41]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn_model = knn.fit(X_train,Y_train)
knn_model

KNeighborsClassifier()

In [42]:
knn_pred = knn.predict(X_test)
knn_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [43]:
accuracy_score(Y_test,knn_pred)*100

95.93333333333334

In [44]:
with open(r"RFC_Model.pkl", "wb") as f:
    pickle.dump(rfc_model, f)

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
